### ISSUE TITLE
Provisionar bot

### ISSUE THREAD

**Issue by innng** [innng/promotrackerbot#3]
**Como** um Desenvolvedor do bot
**Eu quero** ter um local para subir as modificações
**Para que** as implementações do bot possam ser feitas e testadas em um ambiente similar ou igual ao de produção

**Acceptance Criteria:**
- Bot está rodando na AWS
- Comunicação básica com o bot pode ser feita via API

**Tasks:**
- [ ] Criar conta AWS
- [ ] Configurar AWS Lambda para receber código do bot
- [ ] Abrir uma rota de comunição com o bot via API Gateway
- [ ] Configurar CI com testes e deploy automático
