### ISSUE TITLE
Encontrar o bot na busca do Telegram

### ISSUE THREAD

**Issue by innng** [innng/promotrackerbot#4]
**Como** um Usuário do Telegram
**Eu quero** buscar pelo nome do bot
**para que** eu possa interagir com ele

**Acceptance Criteria**:
- Usuário consegue colocar o nome do bot na busca
- Resultado da busca retorna nosso bot
- Usuário consegue abrir uma janela de conversa com o bot

**Tasks**:

- [ ] Gerar o token do bot usando a API do Telegram
- [ ] Configurar as informações principais do bot (nome, avatar, etc)
- [ ] Testar a url/username do bot gerado
